name: lunarsite
description: "Emacs.  What else?  A bit of Haskell probablyâ€¦"
url: "http://www.lunaryorn.com"

baseurl: ""

author:
  name: "Sebastian Wiesner"
  email: "me@lunaryorn.com"
  uri: "http://www.lunaryorn.com"
  twitter: "lunaryorn"
  github: "lunaryorn"

github:
  url: "https://github.com/lunaryorn/lunaryorn.github.io"

# Build settings
markdown: kramdown
timezone: "Europe/Berlin"
encoding: "utf-8"
exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"

kramdown:
  auto_ids: true
  auto_id_prefix: "section-"
  header_offset: 1
  smart_quotes: ["apos", "apos", "quot", "quot"]

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
