name: lunaryorn
title: "Emacs.  What else?"
description: "A personal blog about Emacs and functional programming"
logo: '/logo.png'

twitter:
  username: 'lunaryorn'

baseurl: ""

author:
  name: "Sebastian Wiesner"
  email: "me@lunaryorn.com"
  uri: "http://www.lunaryorn.com"

# Build settings
environment: production
timezone: "Europe/Berlin"
encoding: "utf-8"
exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
permalink: "/:year/:month/:day/:title.html"
format:
  date_long: "%B %-d, %Y"
  date_short: "%b %d, %y"
excerpt_separator: "<!--more-->"
markdown: kramdown

gems:
  - jekyll-seo-tag

sass:
  style: compressed

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: {}
  # Github Flavoured Markdown with fancy fenced code blocks, but without the
  # stupid hard-wrap rule, please.
  input: GFM
  hard_wrap: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
