name: lunarsite
description: "Emacs.  What else?  A bit of Haskell probablyâ€¦"
url: "http://www.lunaryorn.com"

baseurl: ""

author:
  name: "Sebastian Wiesner"
  email: "me@lunaryorn.com"
  uri: "http://www.lunaryorn.com"
  twitter: "@lunaryorn"
  github: "lunaryorn"

github:
  url: "https://github.com/lunaryorn/lunaryorn.github.io"

# Build settings
markdown: redcarpet
timezone: "Europe/Berlin"
encoding: "utf-8"
exclude:
  - "Rakefile"
  - "Gemfile"
  - "Gemfile.lock"
  - "vendor"
format:
  date_long: "%B %-d, %Y"
  date_short: "%b %d, %y"
excerpt_separator: "<!--more-->"

gems:
  - jekyll-feed

feed:
  path: "feed.atom"

sass:
  style: compressed

redcarpet:
  extensions:
    - no_intra_emphasis
    - tables
    - footnotes
    - with_toc_data

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
